# Generated by Django 4.2.4 on 2023-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('referencia_motocicleta', models.CharField(max_length=30)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('motivo_reparacion', models.CharField(max_length=50)),
                ('numero_turno', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
