# Generated by Django 4.2.4 on 2023-10-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='numero_turno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
