# Generated by Django 4.2.4 on 2023-10-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0002_alter_turno_numero_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('motocicleta', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('detalles_reparacion', models.TextField()),
                ('mecanico', models.CharField(max_length=100)),
                ('estado_motocicleta', models.CharField(choices=[('Malo', 'Malo 😥'), ('Regular', 'Regular 😬'), ('Bueno', 'Bueno 🙂'), ('Excelente', 'Excelente 😁')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='turno',
            name='numero_turno',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
