# Generated by Django 4.2.4 on 2023-10-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0003_informereparacion_alter_turno_numero_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='informereparacion',
            name='evidencia_fotografica',
            field=models.ImageField(default='default.jpg', upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='informereparacion',
            name='estado_motocicleta',
            field=models.CharField(max_length=100),
        ),
    ]
