# Generated by Django 4.2.6 on 2023-10-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0004_informereparacion_evidencia_fotografica_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformeReparacion',
        ),
    ]
